# main.yml
name: deploy to aliyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: '-avzr --delete'
          SOURCE: 'dist/'
          REMOTE_HOST: '8.135.39.65'
          REMOTE_USER: 'root'
          TARGET: ''
