# main.yml
name: deploy to aliyun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      - name: use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: '8.135.39.65'
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}
          local_path: './dist/*'
          remote_path: '/root/webapp'
          args: '-o ConnectTimeout=5'
